//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuleOfEngine_Scheduler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinocartDemo1Entities : DbContext
    {
        public FinocartDemo1Entities()
            : base("name=FinocartDemo1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<AnchorNotification> AnchorNotifications { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<LookupDetail> LookupDetails { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ModuleMaster> ModuleMasters { get; set; }
        public virtual DbSet<PaymentDueTodayTemplate> PaymentDueTodayTemplates { get; set; }
        public virtual DbSet<SetBankAmountLimit> SetBankAmountLimits { get; set; }
        public virtual DbSet<BankNotification> BankNotifications { get; set; }
        public virtual DbSet<BankSetLimitMailTemplate> BankSetLimitMailTemplates { get; set; }
    }
}
