//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finocart_Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnchorCompanies
    {
        public int AnchorCompID { get; set; }
        public string AnchorCompName { get; set; }
        public string ContactName { get; set; }
        public string ContactNo { get; set; }
        public string EmailID { get; set; }
        public Nullable<long> InvoiceAssWith { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
