//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finocart_Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoFundingRate
    {
        public long AutoFudngId { get; set; }
        public decimal DiscuntRate { get; set; }
        public System.DateTime DiscuntVlidDate { get; set; }
    }
}
