//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finocart_Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class BucketManagement
    {
        public long BucketID { get; set; }
        public string BucketName { get; set; }
        public Nullable<int> BucketStatus { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> ValidUptoDate { get; set; }
        public Nullable<System.DateTime> BucketCreatedDate { get; set; }
        public Nullable<long> BucketCreatedBy { get; set; }
        public Nullable<long> BucketModifiedBy { get; set; }
        public Nullable<System.DateTime> BucketModifiedAt { get; set; }
    }
}
