//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finocart_Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorTracer
    {
        public int ErrorID { get; set; }
        public Nullable<int> ErrorNumber { get; set; }
        public Nullable<int> ErrorState { get; set; }
        public Nullable<int> ErrorSeverity { get; set; }
        public Nullable<int> ErrorLine { get; set; }
        public string ErrorProc { get; set; }
        public string ErrorMsg { get; set; }
        public string UserName { get; set; }
        public string HostName { get; set; }
        public Nullable<System.DateTime> ErrorDate { get; set; }
    }
}
