//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finocart_Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogManagement
    {
        public long Id { get; set; }
        public string ControllerName { get; set; }
        public string MethodName { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> ErrorLine { get; set; }
        public string UrlName { get; set; }
        public string BrowserName { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
