//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finocart_Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchHistory
    {
        public long ID { get; set; }
        public string PageName { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string SearchKeyValue { get; set; }
        public Nullable<int> MaxSearchLimit { get; set; }
    }
}
