//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finocart_Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetBankAmountLimit
    {
        public int id { get; set; }
        public int Anchor_id { get; set; }
        public string Anchor_Name { get; set; }
        public Nullable<decimal> Available_Limits { get; set; }
        public Nullable<decimal> Utilized_Limits { get; set; }
        public Nullable<decimal> Interest_rate { get; set; }
        public Nullable<System.DateTime> Validity_upto { get; set; }
        public Nullable<decimal> Draw_funds { get; set; }
        public string Additional_document { get; set; }
        public Nullable<int> NumberOfDays { get; set; }
        public string Comment { get; set; }
        public string RequestStatus { get; set; }
        public string Documentation { get; set; }
        public string BankName { get; set; }
        public string AnchorEmail { get; set; }
        public string ModifiedUserName { get; set; }
        public Nullable<System.DateTime> ValidityFromto { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string ODBD { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> Approvaldate { get; set; }
        public Nullable<decimal> Remaining_avail_bal { get; set; }
        public Nullable<int> KYCStatus { get; set; }
    }
}
