//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finocart_Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public string Designation { get; set; }
        public string RolesAccess { get; set; }
        public Nullable<int> RoleAccessID { get; set; }
        public Nullable<int> AccessViewID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string PANNumber { get; set; }
        public bool IsTemporaryPassword { get; set; }
        public Nullable<int> LoginAttempt { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual LookupDetails LookupDetails { get; set; }
    }
}
