//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finocart_Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.VendorDiscMap = new HashSet<VendorDiscMap>();
        }
    
        public int VendorID { get; set; }
        public string VendorName { get; set; }
        public string ContactNumber { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> MaxLimit { get; set; }
        public Nullable<int> VendorStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public string ContactPersonName { get; set; }
        public Nullable<int> ContactPersonNumber { get; set; }
        public string ContactPersonEmailId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string PANNumber { get; set; }
        public string ContactPersonDesignation { get; set; }
        public string Password { get; set; }
        public bool IsTemporaryPassword { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        public virtual ModuleMaster ModuleMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorDiscMap> VendorDiscMap { get; set; }
    }
}
