//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finocart_Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorDiscMap
    {
        public long ID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<long> DiscountAmt { get; set; }
        public Nullable<bool> IsDiscountApplied { get; set; }
        public Nullable<int> VendorID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual VendorDiscMap VendorDiscMap1 { get; set; }
        public virtual VendorDiscMap VendorDiscMap2 { get; set; }
    }
}
