//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelUpload.Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadExcelPath
    {
        public long ID { get; set; }
        public string Path { get; set; }
        public string FileName { get; set; }
        public Nullable<long> Uploaded { get; set; }
        public Nullable<long> Remaining { get; set; }
        public string Name { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Logs { get; set; }
    }
}
